### ISSUE TITLE
Stop using two content items to render content

### ISSUE THREAD

**Issue by fofr** [alphagov/specialist-frontend#128]
From what I can tell, after the content item for the specialist document is requested, the frontend uses the base path returned to make another call to the parent finder content item. These two content items are used to render content:
https://github.com/alphagov/specialist-frontend/blob/master/app/controllers/specialist_documents_controller.rb#L34-L36

This violates the frontend design principle of providing everything needed to render content in a single content item. This isn't recent code, it represents a temporary workaround while concepts like dependency resolution and parents were not yet available in the publishing API.

We should update this pattern to make specialist documents consistent with other content items and more resilient.

@tijmenb

**Comment by tijmenb** [comment]
Seems like a good idea, go for it 👍

**Comment by fofr** [comment]
Being tracked here:
https://trello.com/c/6CBttvZL/1-specialist-frontend-uses-2x-content-items-to-render-a-single-page

**Comment by fofr** [comment]
All content is now available in the specialist document content item. This will be rendered by government-frontend.
